name: Build and Deploy UI
on:
  push:
    branches: [ "Dev" ]
  workflow_dispatch:

env:
  APP_LOCATION: "/flightTracking" # location of your client code
  OUTPUT_LOCATION: "/dist/flight-tracking/browser" # location of client code build output

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Deploy to Azure
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          node-version: '20.x'
          
